apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-billing-datadog-api-key
  namespace: sre
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.clusterSecretStore }}
  target:
    name: gcp-billing-datadog-api-key
    creationPolicy: Owner
  data:
    - secretKey: gcp-billing-datadog-api-key
      remoteRef:
        key: gcp-billing-datadog-api-key
